#!/bin/sh
#
# @name QuadrotorX SITL for SIH
#
# @type Quadrotor
#
# @maintainer Romain Chiappinelli <romain.chiap@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=quadx}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default EKF2_GPS_DELAY 0

param set SIH_VEHICLE_TYPE 0

# Easydocking carrier tuning: allow higher horizontal speed/accel in OFFBOARD so the
# multicopter can match the fixed-wing mini and avoid large terminal XY separation.
# (Defaults: MPC_XY_VEL_MAX=12, MPC_ACC_HOR=3, MPC_XY_ERR_MAX=2)
param set MPC_XY_VEL_MAX 16
param set MPC_VEL_MANUAL 16
param set MPC_XY_CRUISE 14
param set MPC_ACC_HOR 6
param set MPC_ACC_HOR_MAX 8
param set MPC_JERK_AUTO 12
param set MPC_JERK_MAX 20
param set MPC_XY_ERR_MAX 10

# Note: SIH can become unstable with very high tilt limits at high speed; keep a moderate
# margin above the default 45 deg while avoiding attitude-health failsafes.
param set MPC_TILTMAX_AIR 55
param set MPC_TILTMAX_LND 45

param show MPC_XY_VEL_MAX
param show MPC_ACC_HOR
param show MPC_XY_ERR_MAX
param show MPC_TILTMAX_AIR

param save
