#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

set +u
source "$ROOT_DIR/scripts/setup_local_env.sh" >/dev/null
set -u

CARRIER_OFFSET_X="${CARRIER_OFFSET_X:-54.0}" \
CARRIER_OFFSET_Y="${CARRIER_OFFSET_Y:--30.0}" \
MINI_ORBIT_START_PHASE_DEG="${MINI_ORBIT_START_PHASE_DEG:-180.0}" \
EXPERIMENT_DURATION_SEC="${EXPERIMENT_DURATION_SEC:-90.0}" \
START_RVIZ="${START_RVIZ:-true}" \
AUTO_START_USE_STATE_MACHINE_TRIGGER="${AUTO_START_USE_STATE_MACHINE_TRIGGER:-true}" \
AUTO_START_USE_LOCAL_MIN_TRIGGER="${AUTO_START_USE_LOCAL_MIN_TRIGGER:-false}" \
AUTO_START_TIMEOUT_SEC="${AUTO_START_TIMEOUT_SEC:-85.0}" \
AUTO_START_MIN_WAIT_SEC="${AUTO_START_MIN_WAIT_SEC:-18.0}" \
AUTO_START_SM_WINDOW_START_SEC="${AUTO_START_SM_WINDOW_START_SEC:-18.0}" \
AUTO_START_SM_WINDOW_END_SEC="${AUTO_START_SM_WINDOW_END_SEC:--1.0}" \
AUTO_START_SM_OBSERVE_DISTANCE="${AUTO_START_SM_OBSERVE_DISTANCE:-24.0}" \
AUTO_START_SM_OBSERVE_ABS_Y="${AUTO_START_SM_OBSERVE_ABS_Y:-16.0}" \
AUTO_START_SM_TRIGGER_DISTANCE="${AUTO_START_SM_TRIGGER_DISTANCE:-12.0}" \
AUTO_START_SM_TRIGGER_ABS_Y="${AUTO_START_SM_TRIGGER_ABS_Y:-8.0}" \
AUTO_START_SM_TRIGGER_ABS_X="${AUTO_START_SM_TRIGGER_ABS_X:-10.0}" \
AUTO_START_SM_MIN_CONVERGING_SAMPLES="${AUTO_START_SM_MIN_CONVERGING_SAMPLES:-6}" \
AUTO_START_SM_ENTER_MAX_CLOSING_RATE="${AUTO_START_SM_ENTER_MAX_CLOSING_RATE:--0.15}" \
AUTO_START_SM_STAY_MAX_CLOSING_RATE="${AUTO_START_SM_STAY_MAX_CLOSING_RATE:-0.25}" \
AUTO_START_SM_REBOUND_MARGIN="${AUTO_START_SM_REBOUND_MARGIN:-0.08}" \
AUTO_START_SM_MAX_RELATIVE_SPEED="${AUTO_START_SM_MAX_RELATIVE_SPEED:-9.5}" \
AUTO_START_SM_STAGNATION_SAMPLES="${AUTO_START_SM_STAGNATION_SAMPLES:-4}" \
AUTO_START_SM_TRIGGER_MIN_CLOSING_RATE="${AUTO_START_SM_TRIGGER_MIN_CLOSING_RATE:--0.25}" \
AUTO_START_SM_TRIGGER_MAX_ABS_VY="${AUTO_START_SM_TRIGGER_MAX_ABS_VY:-5.0}" \
AUTO_START_SM_TRIGGER_PROJECTED_ABS_Y="${AUTO_START_SM_TRIGGER_PROJECTED_ABS_Y:-2.2}" \
AUTO_START_SM_ENABLE_SEARCH_TRIGGER="${AUTO_START_SM_ENABLE_SEARCH_TRIGGER:-true}" \
AUTO_START_SM_SEARCH_TRIGGER_MIN_DISTANCE="${AUTO_START_SM_SEARCH_TRIGGER_MIN_DISTANCE:-16.0}" \
AUTO_START_SM_SEARCH_TRIGGER_MAX_DISTANCE="${AUTO_START_SM_SEARCH_TRIGGER_MAX_DISTANCE:-20.5}" \
AUTO_START_SM_SEARCH_TRIGGER_ABS_Y="${AUTO_START_SM_SEARCH_TRIGGER_ABS_Y:-14.0}" \
AUTO_START_SM_SEARCH_TRIGGER_MAX_CLOSING_RATE="${AUTO_START_SM_SEARCH_TRIGGER_MAX_CLOSING_RATE:-2.0}" \
AUTO_START_SM_SEARCH_TRIGGER_PROJECTED_ABS_Y="${AUTO_START_SM_SEARCH_TRIGGER_PROJECTED_ABS_Y:-1.2}" \
AUTO_START_SM_SEARCH_MIN_SAMPLES="${AUTO_START_SM_SEARCH_MIN_SAMPLES:-4}" \
"$ROOT_DIR/scripts/run_px4_sih_docking_experiment.sh"
